/* Generated By:JavaCC: Do not edit this line. compConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface compConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ASIGNACION = 1;
  /** RegularExpression Id. */
  int PLUS = 2;
  /** RegularExpression Id. */
  int MINUS = 3;
  /** RegularExpression Id. */
  int MULTIPLY = 4;
  /** RegularExpression Id. */
  int DIVIDE = 5;
  /** RegularExpression Id. */
  int INCR = 6;
  /** RegularExpression Id. */
  int DECR = 7;
  /** RegularExpression Id. */
  int INICIAR = 8;
  /** RegularExpression Id. */
  int REPRODUCIR = 9;
  /** RegularExpression Id. */
  int INVERNA = 10;
  /** RegularExpression Id. */
  int DERO = 11;
  /** RegularExpression Id. */
  int COMENZAR = 12;
  /** RegularExpression Id. */
  int TERMINAR = 13;
  /** RegularExpression Id. */
  int COMPROBAR = 14;
  /** RegularExpression Id. */
  int RUTINA = 15;
  /** RegularExpression Id. */
  int HUMEDAD = 16;
  /** RegularExpression Id. */
  int SI = 17;
  /** RegularExpression Id. */
  int NO = 18;
  /** RegularExpression Id. */
  int COMPLEMENTO = 19;
  /** RegularExpression Id. */
  int DURANTE = 20;
  /** RegularExpression Id. */
  int SIEMPRE = 21;
  /** RegularExpression Id. */
  int MIN = 22;
  /** RegularExpression Id. */
  int HR = 23;
  /** RegularExpression Id. */
  int GRADOS = 24;
  /** RegularExpression Id. */
  int TEMPERATURA_ACTUAL = 25;
  /** RegularExpression Id. */
  int MINIMO = 26;
  /** RegularExpression Id. */
  int MAXIMO = 27;
  /** RegularExpression Id. */
  int INCREMENTAR = 28;
  /** RegularExpression Id. */
  int DECREMENTAR = 29;
  /** RegularExpression Id. */
  int VOLUMEN = 30;
  /** RegularExpression Id. */
  int MUSICA = 31;
  /** RegularExpression Id. */
  int DETENER = 32;
  /** RegularExpression Id. */
  int PAUSAR = 33;
  /** RegularExpression Id. */
  int POSICION = 34;
  /** RegularExpression Id. */
  int CONTINUAR = 35;
  /** RegularExpression Id. */
  int FERTILIZANTE = 36;
  /** RegularExpression Id. */
  int FERTLIQ = 37;
  /** RegularExpression Id. */
  int SOLIDO = 38;
  /** RegularExpression Id. */
  int CORDX = 39;
  /** RegularExpression Id. */
  int CORDY = 40;
  /** RegularExpression Id. */
  int POR = 41;
  /** RegularExpression Id. */
  int REPETIR = 42;
  /** RegularExpression Id. */
  int EMPEZAR = 43;
  /** RegularExpression Id. */
  int RIEGO = 44;
  /** RegularExpression Id. */
  int LIQUIDO = 45;
  /** RegularExpression Id. */
  int MAS = 46;
  /** RegularExpression Id. */
  int MENOS = 47;
  /** RegularExpression Id. */
  int SECTOR = 48;
  /** RegularExpression Id. */
  int TIPO = 49;
  /** RegularExpression Id. */
  int INVERNADERO = 50;
  /** RegularExpression Id. */
  int LUMEN = 51;
  /** RegularExpression Id. */
  int LPAREN = 52;
  /** RegularExpression Id. */
  int RPAREN = 53;
  /** RegularExpression Id. */
  int LBRACE = 54;
  /** RegularExpression Id. */
  int RBRACE = 55;
  /** RegularExpression Id. */
  int LBRACKET = 56;
  /** RegularExpression Id. */
  int RBRACKET = 57;
  /** RegularExpression Id. */
  int SEMICOLON = 58;
  /** RegularExpression Id. */
  int COMMA = 59;
  /** RegularExpression Id. */
  int DOT = 60;
  /** RegularExpression Id. */
  int DOUBLECOMMA = 61;
  /** RegularExpression Id. */
  int EQ = 62;
  /** RegularExpression Id. */
  int LE = 63;
  /** RegularExpression Id. */
  int MN = 64;
  /** RegularExpression Id. */
  int GE = 65;
  /** RegularExpression Id. */
  int GR = 66;
  /** RegularExpression Id. */
  int NE = 67;
  /** RegularExpression Id. */
  int OR = 68;
  /** RegularExpression Id. */
  int AND = 69;
  /** RegularExpression Id. */
  int TEMPERATURA = 70;
  /** RegularExpression Id. */
  int VAHO = 71;
  /** RegularExpression Id. */
  int LUZ = 72;
  /** RegularExpression Id. */
  int LUMINOSIDAD = 73;
  /** RegularExpression Id. */
  int NUMERO = 74;
  /** RegularExpression Id. */
  int CADENA = 75;
  /** RegularExpression Id. */
  int CADENADOS = 76;
  /** RegularExpression Id. */
  int IDENTIFIER = 77;
  /** RegularExpression Id. */
  int DECIMAL = 78;
  /** RegularExpression Id. */
  int TEMPER = 79;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"++\"",
    "\"--\"",
    "\"iniciar\"",
    "\"reproducir\"",
    "\"inverna\"",
    "\"dero\"",
    "\"public static void Main()\"",
    "\"terminar\"",
    "\"comprobar\"",
    "\"rutina\"",
    "\"humedad\"",
    "\"siiii\"",
    "\"noooo\"",
    "\"complemento\"",
    "\"durante\"",
    "\"siempre\"",
    "\"min\"",
    "\"hr\"",
    "\"grados\"",
    "\"temperatura_actual\"",
    "\"minimo\"",
    "\"maximo\"",
    "\"incrementar\"",
    "\"decrementar\"",
    "\"volumen\"",
    "\"musica\"",
    "\"detener\"",
    "\"pausar\"",
    "\"posicion\"",
    "\"continuar\"",
    "\"fertilizante\"",
    "\"fertliq\"",
    "\"solido\"",
    "\"cordx\"",
    "\"cordy\"",
    "\"por\"",
    "\"repetir\"",
    "\"empezar\"",
    "\"riego\"",
    "\"liquido\"",
    "\"mas\"",
    "\"menos\"",
    "\"sector\"",
    "\"tipo\"",
    "\"invernadero\"",
    "\"lumen\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"\\\"\"",
    "\"==\"",
    "\"<=\"",
    "\"<\"",
    "\">=\"",
    "\">\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"temperatura\"",
    "\"vaho\"",
    "\"luz\"",
    "\"luminosidad\"",
    "<NUMERO>",
    "\"si\"",
    "\"no\"",
    "<IDENTIFIER>",
    "<DECIMAL>",
    "<TEMPER>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"\\t\"",
  };

}
